keys:
  - &admin_atlas age1kevatctlk4nhhr5vjv8yz8qsynszhx4g92tjhh9v8fnhc5gj347qksaew3
  - &server_atlas age1c5r7xpvwxurf098l0ds3ztyntzq22gj8lf8tc3padhr0pynjndvsqq0g85
  - &admin_scarab age1vfvrztpxfd0wzjlr4m3j06v0zpad5rf653we9uy0jpfx3gwmw4sqjn5p0a 
  - &server_scarab age1rwaxwvnhzmg5p6d5uuy7tas2fd8yxt064r3h9pws2m46gvt90eeq8e0vxp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_atlas
      - *admin_scarab
      - *server_atlas
      - *server_scarab
