"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](green)\
[ 󰊟 ](bg:green fg:black)\
[](bg:red fg:green)\
$directory\
[](fg:red bg:magenta)\
$git_branch\
$git_status\
[](fg:magenta bg:yellow)\
$nix_shell\
[](fg:yellow bg:blue)\
$nodejs\
$rust\
$golang\
$php\
[](fg:blue bg:dgray)\
$time\
[ ](fg:dgray)\
\n$character"""

[directory]
style = "fg:black bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Imagenes" = " "

[git_branch]
symbol = ""
style = "bg:magenta"
format = '[[ $symbol $branch ](fg:black bg:magenta)]($style)'

[git_status]
style = "bg:magenta"
format = '[[($all_status$ahead_behind )](fg:black bg:magenta)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:black bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:black bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:black bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:black bg:blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:dgray"
format = '[[  $time ](fg:lgray bg:dgray)]($style)'

[nix_shell]
disabled = false
style = "bg:yellow"
format = '[[  $state(\($name\)) ](fg:black bg:yellow)]($style)'

[character]
success_symbol = """
 [⊂\\(](bold white)\
[󰉊 ](bold green)\
[^w^](bold white)\
[\\)つ](bold white)\
 """

error_symbol = """
 [╭\\(](bold white)\
[󰉊 ](bold red)\
[╥﹏╥](bold white)\
[\\)╮](bold white)\
 """
