"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](green)\
[ 󰊟 ](bg:green fg:black)\
[](bg:red fg:green)\
$directory\
[](fg:red bg:magenta)\
$git_branch\
$git_status\
[](fg:magenta bg:blue)\
$nodejs\
$rust\
$golang\
$php\
[](fg:blue bg:dgray)\
$time\
[ ](fg:dgray)\
\n$character"""

[directory]
style = "fg:black bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Imagenes" = " "

[git_branch]
symbol = ""
style = "bg:magenta"
format = '[[ $symbol $branch ](fg:black bg:magenta)]($style)'

[git_status]
style = "bg:magenta"
format = '[[($all_status$ahead_behind )](fg:black bg:magenta)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:red bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:red bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:red bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:red bg:blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:dgray"
format = '[[  $time ](fg:lgray bg:dgray)]($style)'

[character]
success_symbol = """
[૮\\(](bold white)\
[󰉊 ](bold magenta)\
[◡](bold white)\
[‿](bold white)\
[◡](bold white)\
[\\)づ](bold white)\
[ ](bold green)"""

error_symbol = """
[╭\\(](bold white)\
[\ue34a ](bold cyan)\
[ò](bold white)\
[_](bold white)\
[ó](bold white)\
[\\)ง\\]](bold white)\
[ \uff61\u00b0\u25cb](bold red)"""
