# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.3.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.3.0.tgz";
        sha512 = "30iZtAPgz+LTIYoeivqYo853f02jBYSd5uGnGpkFV0M3xOt9aN73erkgYAmZU43x4VfqcnLxW9Kpg3R5LC4YYw==";
      };
    };
    "@img/colour-1.0.0" = {
      name = "_at_img_slash_colour";
      packageName = "@img/colour";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@img/colour/-/colour-1.0.0.tgz";
        sha512 = "A5P/LfWGFSl6nsckYtjw9da+19jB8hkJ6ACTGcDfEJ0aE+l2n2El7dsVM7UVHZQ9s2lmYMWlrS21YLy2IR1LUw==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.31" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
        sha512 = "zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/marked-5.0.2" = {
      name = "_at_types_slash_marked";
      packageName = "@types/marked";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/marked/-/marked-5.0.2.tgz";
        sha512 = "OucS4KMHhFzhz27KxmWg7J+kIYqyqoW5kdIEI319hqARQQUTqhao3M/F+uFnDXD0Rg72iDDZxZNxq5gvctmLlg==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "bcryptjs-2.4.3" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.4.3.tgz";
        sha512 = "V/Hy/X9Vt7f3BbPJEi8BdVFMByHi+jNXrYkW3huaybV/kQ0KJg0Y6PkEMbn+zeT+i+SiKZ/HMqJGIIt4LZDqNQ==";
      };
    };
    "code-red-1.0.4" = {
      name = "code-red";
      packageName = "code-red";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-red/-/code-red-1.0.4.tgz";
        sha512 = "7qJWqItLA8/VPVlKJlFXU+NBlo/qyfs39aJcuMT/2ere32ZqvF5OSxgdM5xOfJJ7O429gg2HM47y8v9P+9wrNw==";
      };
    };
    "css-tree-2.3.1" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-2.3.1.tgz";
        sha512 = "6Fv1DV/TYw//QF5IzQdqsNDjx/wc8TrMBZsqjL9eW01tWb7R7k/mq+/VXfJCl7SoD5emsJop9cOByJZfs8hYIw==";
      };
    };
    "detect-libc-2.1.1" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.1.tgz";
        sha512 = "ecqj/sy1jcK1uWrwpR67UhYrIFQ+5WlGxth34WquCbamhFA6hkkwiu37o6J5xCHdo1oixJRfVRw+ywV+Hq/0Aw==";
      };
    };
    "estree-walker-3.0.3" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-3.0.3.tgz";
        sha512 = "7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "magic-string-0.30.19" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.19.tgz";
        sha512 = "2N21sPY9Ws53PZvsEpVtNuSW+ScYbQdp4b9qUaL+9QkHUrGFKo56Lg9Emg5s9V/qrtNBmiR01sYhUOwu3H+VOw==";
      };
    };
    "marked-5.1.2" = {
      name = "marked";
      packageName = "marked";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-5.1.2.tgz";
        sha512 = "ahRPGXJpjMjwSOlBoTMZAK7ATXkli5qCPxZ21TG44rx1KEo44bii4ekgTDQPNRQ4Kh7JMb9Ub1PVk1NxRSsorg==";
      };
    };
    "mdn-data-2.0.30" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.30.tgz";
        sha512 = "GaqWWShW4kv/G9IEucWScBx9G1/vsFZZJUO+tD26M8J8z3Kw5RDQjaoZe03YAClgeS/SWPOcb4nkFBTEi5DUEA==";
      };
    };
    "periscopic-3.1.0" = {
      name = "periscopic";
      packageName = "periscopic";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/periscopic/-/periscopic-3.1.0.tgz";
        sha512 = "vKiQ8RRtkl9P+r/+oefh25C3fhybptkHKCZSPlcXiJux2tJF55GnEj3BVn4A5gKfq9NWWXXrxkHBwVPUfH0opw==";
      };
    };
    "semver-7.7.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.2.tgz";
        sha512 = "RF0Fw+rO5AMf9MAyaRXI4AV0Ulj5lMHqVxxdSgiVbixSCXoEmmX/jk0CuJw4+3SqroYO9VoUh+HcuJivvtJemA==";
      };
    };
    "sharp-0.34.4" = {
      name = "sharp";
      packageName = "sharp";
      version = "0.34.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sharp/-/sharp-0.34.4.tgz";
        sha512 = "FUH39xp3SBPnxWvd5iib1X8XY7J0K0X7d93sie9CJg2PO8/7gmg89Nve6OjItK53/MlAushNNxteBYfM6DEuoA==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "svelte-4.2.20" = {
      name = "svelte";
      packageName = "svelte";
      version = "4.2.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-4.2.20.tgz";
        sha512 = "eeEgGc2DtiUil5ANdtd8vPwt9AgaMdnuUFnPft9F5oMvU/FHu5IHFic+p1dR/UOB7XU2mX2yHW+NcTch4DCh5Q==";
      };
    };
    "svelte-markdown-0.4.1" = {
      name = "svelte-markdown";
      packageName = "svelte-markdown";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-markdown/-/svelte-markdown-0.4.1.tgz";
        sha512 = "pOlLY6EruKJaWI9my/2bKX8PdTeP5CM0s4VMmwmC2prlOkjAf+AOmTM4wW/l19Y6WZ87YmP8+ZCJCCwBChWjYw==";
      };
    };
  };
  args = {
    name = "volbot-org";
    packageName = "volbot-org";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@ampproject/remapping-2.3.0"
      sources."@img/colour-1.0.0"
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.31"
      sources."@types/estree-1.0.8"
      sources."@types/marked-5.0.2"
      sources."acorn-8.15.0"
      sources."aria-query-5.3.2"
      sources."axobject-query-4.1.0"
      sources."bcryptjs-2.4.3"
      sources."code-red-1.0.4"
      sources."css-tree-2.3.1"
      sources."detect-libc-2.1.1"
      sources."estree-walker-3.0.3"
      sources."is-reference-3.0.3"
      sources."locate-character-3.0.0"
      sources."magic-string-0.30.19"
      sources."marked-5.1.2"
      sources."mdn-data-2.0.30"
      sources."periscopic-3.1.0"
      sources."semver-7.7.2"
      sources."sharp-0.34.4"
      sources."source-map-js-1.2.1"
      sources."svelte-4.2.20"
      sources."svelte-markdown-0.4.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
